#pragma once

namespace Rendering
{
typedef unsigned int Color;

extern unsigned __int8 colorToR(const Color& color);
extern unsigned __int8 colorToG(const Color& color);
extern unsigned __int8 colorToB(const Color& color);
extern unsigned __int8 colorToA(const Color& color);

namespace Colors
{
inline static constexpr Color AliceBlue(0xF0F8FFFF);
inline static constexpr Color AntiqueWhite(0xFAEBD7FF);
inline static constexpr Color Aqua(0x00FFFFFF);
inline static constexpr Color Aquamarine(0x7FFFD4FF);
inline static constexpr Color Azure(0xF0FFFFFF);
inline static constexpr Color Beige(0xF5F5DCFF);
inline static constexpr Color Bisque(0xFFE4C4FF);
inline static constexpr Color Black(0x000000FF);
inline static constexpr Color BlanchedAlmond(0xFFEBCDFF);
inline static constexpr Color Blue(0x0000FFFF);
inline static constexpr Color BlueViolet(0x8A2BE2FF);
inline static constexpr Color Brown(0xA52A2AFF);
inline static constexpr Color BurlyWood(0xDEB887FF);
inline static constexpr Color CadetBlue(0x5F9EA0FF);
inline static constexpr Color Chartreuse(0x7FFF00FF);
inline static constexpr Color Chocolate(0xD2691EFF);
inline static constexpr Color Coral(0xFF7F50FF);
inline static constexpr Color CornflowerBlue(0x6495EDFF);
inline static constexpr Color Cornsilk(0xFFF8DCFF);
inline static constexpr Color Crimson(0xDC143CFF);
inline static constexpr Color Cyan(0x00FFFFFF);
inline static constexpr Color DarkBlue(0x00008BFF);
inline static constexpr Color DarkCyan(0x008B8BFF);
inline static constexpr Color DarkGoldenrod(0xB8860BFF);
inline static constexpr Color DarkGray(0xA9A9A9FF);
inline static constexpr Color DarkGreen(0x006400FF);
inline static constexpr Color DarkKhaki(0xBDB76BFF);
inline static constexpr Color DarkMagenta(0x8B008BFF);
inline static constexpr Color DarkOliveGreen(0x556B2FFF);
inline static constexpr Color DarkOrange(0xFF8C00FF);
inline static constexpr Color DarkOrchid(0x9932CCFF);
inline static constexpr Color DarkRed(0x8B0000FF);
inline static constexpr Color DarkSalmon(0xE9967AFF);
inline static constexpr Color DarkSeaGreen(0x8FBC8FFF);
inline static constexpr Color DarkSlateBlue(0x483D8BFF);
inline static constexpr Color DarkSlateGray(0x2F4F4FFF);
inline static constexpr Color DarkTurquoise(0x00CED1FF);
inline static constexpr Color DarkViolet(0x9400D3FF);
inline static constexpr Color DeepPink(0xFF1493FF);
inline static constexpr Color DeepSkyBlue(0x00BFFFFF);
inline static constexpr Color DimGray(0x696969FF);
inline static constexpr Color DodgerBlue(0x1E90FFFF);
inline static constexpr Color FireBrick(0xB22222FF);
inline static constexpr Color FloralWhite(0xFFFAF0FF);
inline static constexpr Color ForestGreen(0x228B22FF);
inline static constexpr Color Fuchsia(0xFF00FFFF);
inline static constexpr Color Gainsboro(0xDCDCDCFF);
inline static constexpr Color GhostWhite(0xF8F8FFFF);
inline static constexpr Color Gold(0xFFD700FF);
inline static constexpr Color Goldenrod(0xDAA520FF);
inline static constexpr Color Gray(0x808080FF);
inline static constexpr Color Green(0x008000FF);
inline static constexpr Color GreenYellow(0xADFF2FFF);
inline static constexpr Color Honeydew(0xF0FFF0FF);
inline static constexpr Color HotPink(0xFF69B4FF);
inline static constexpr Color IndianRed(0xCD5C5CFF);
inline static constexpr Color Indigo(0x4B0082FF);
inline static constexpr Color Ivory(0xFFFFF0FF);
inline static constexpr Color Khaki(0xF0E68CFF);
inline static constexpr Color Lavender(0xE6E6FAFF);
inline static constexpr Color LavenderBlush(0xFFF0F5FF);
inline static constexpr Color LawnGreen(0x7CFC00FF);
inline static constexpr Color LemonChiffon(0xFFFACDFF);
inline static constexpr Color LightBlue(0xADD8E6FF);
inline static constexpr Color LightCoral(0xF08080FF);
inline static constexpr Color LightCyan(0xE0FFFFFF);
inline static constexpr Color LightGoldenrodYellow(0xFAFAD2FF);
inline static constexpr Color LightGreen(0x90EE90FF);
inline static constexpr Color LightGrey(0xD3D3D3FF);
inline static constexpr Color LightPink(0xFFB6C1FF);
inline static constexpr Color LightSalmon(0xFFA07AFF);
inline static constexpr Color LightSeaGreen(0x20B2AAFF);
inline static constexpr Color LightSkyBlue(0x87CEFAFF);
inline static constexpr Color LightSlateGray(0x778899FF);
inline static constexpr Color LightSteelBlue(0xB0C4DEFF);
inline static constexpr Color LightYellow(0xFFFFE0FF);
inline static constexpr Color Lime(0x00FF00FF);
inline static constexpr Color LimeGreen(0x32CD32FF);
inline static constexpr Color Linen(0xFAF0E6FF);
inline static constexpr Color Magenta(0xFF00FFFF);
inline static constexpr Color Maroon(0x800000FF);
inline static constexpr Color MediumAquamarine(0x66CDAAFF);
inline static constexpr Color MediumBlue(0x0000CDFF);
inline static constexpr Color MediumOrchid(0xBA55D3FF);
inline static constexpr Color MediumPurple(0x9370DBFF);
inline static constexpr Color MediumSeaGreen(0x3CB371FF);
inline static constexpr Color MediumSlateBlue(0x7B68EEFF);
inline static constexpr Color MediumSpringGreen(0x00FA9AFF);
inline static constexpr Color MediumTurquoise(0x48D1CCFF);
inline static constexpr Color MediumVioletRed(0xC71585FF);
inline static constexpr Color MidnightBlue(0x191970FF);
inline static constexpr Color MintCream(0xF5FFFAFF);
inline static constexpr Color MistyRose(0xFFE4E1FF);
inline static constexpr Color Moccasin(0xFFE4B5FF);
inline static constexpr Color NavajoWhite(0xFFDEADFF);
inline static constexpr Color Navy(0x000080FF);
inline static constexpr Color OldLace(0xFDF5E6FF);
inline static constexpr Color Olive(0x808000FF);
inline static constexpr Color OliveDrab(0x6B8E23FF);
inline static constexpr Color Orange(0xFFA500FF);
inline static constexpr Color OrangeRed(0xFF4500FF);
inline static constexpr Color Orchid(0xDA70D6FF);
inline static constexpr Color PaleGoldenrod(0xEEE8AAFF);
inline static constexpr Color PaleGreen(0x98FB98FF);
inline static constexpr Color PaleTurquoise(0xAFEEEEFF);
inline static constexpr Color PaleVioletRed(0xDB7093FF);
inline static constexpr Color PapayaWhip(0xFFEFD5FF);
inline static constexpr Color PeachPuff(0xFFDAB9FF);
inline static constexpr Color Peru(0xCD853FFF);
inline static constexpr Color Pink(0xFFC0CBFF);
inline static constexpr Color Plum(0xDDA0DDFF);
inline static constexpr Color PowderBlue(0xB0E0E6FF);
inline static constexpr Color Purple(0x800080FF);
inline static constexpr Color Red(0xFF0000FF);
inline static constexpr Color RosyBrown(0xBC8F8FFF);
inline static constexpr Color RoyalBlue(0x4169E1FF);
inline static constexpr Color SaddleBrown(0x8B4513FF);
inline static constexpr Color Salmon(0xFA8072FF);
inline static constexpr Color SandyBrown(0xF4A460FF);
inline static constexpr Color SeaGreen(0x2E8B57FF);
inline static constexpr Color Seashell(0xFFF5EEFF);
inline static constexpr Color Sienna(0xA0522DFF);
inline static constexpr Color Silver(0xC0C0C0FF);
inline static constexpr Color SkyBlue(0x87CEEBFF);
inline static constexpr Color SlateBlue(0x6A5ACDFF);
inline static constexpr Color SlateGray(0x708090FF);
inline static constexpr Color Snow(0xFFFAFAFF);
inline static constexpr Color SpringGreen(0x00FF7FFF);
inline static constexpr Color SteelBlue(0x4682B4FF);
inline static constexpr Color Tan(0xD2B48CFF);
inline static constexpr Color Teal(0x008080FF);
inline static constexpr Color Thistle(0xD8BFD8FF);
inline static constexpr Color Tomato(0xFF6347FF);
inline static constexpr Color Transparent(0x00000000);
inline static constexpr Color Turquoise(0x40E0D0FF);
inline static constexpr Color Violet(0xEE82EEFF);
inline static constexpr Color Wheat(0xF5DEB3FF);
inline static constexpr Color White(0xFFFFFFFF);
inline static constexpr Color WhiteSmoke(0xF5F5F5FF);
inline static constexpr Color Yellow(0xFFFF00FF);
inline static constexpr Color YellowGreen(0x9ACD32FF);
}
}


